 /*
        
     __|           
     _|    \   _` |
    ___|_| _|\__, |
             ____/ 
    Create by: ukungzulfah ( Eng Javascript Engine )
    
*/
!function(window,document){function _tagDirective(e,t){return system.dataTagDirective[e]=t,eng}function _directive(e,t){return system.dataDirective[e]=t,eng}function _collection(e,t){return system.dataCollection[e]=new Collection(t),eng}function _config(e,t){return system.dataConfig[e]=t,eng}function _service(e,t){return system.dataService[e]=t(),eng}function _module(e,t){return system.dataModule[e]=t,eng}function _factory(e,t){return system.dataFactory[e]=t,eng}function _route(e,t){return system.dataRoute[e]=
t,eng}function getAutoArgument(e,t,n){n=n||{};var a=[];return $.each(e,function(e,o){if(void 0!==n[o])a.push(n[o]);else switch(o){case "$root":a.push(t);break;case "$filter":a.push(system.dataFilter);break;case "$req":a.push(new Request(t));break;case "$request":a.push(new Request(t));break;default:system.dataCollection[o]&&a.push(system.dataCollection[o]),system.dataConfig[o]&&a.push(system.dataConfig[o]),system.dataService[o]&&a.push(system.dataService[o]),system.dataModule[o]&&a.push(new system.dataModule[o](t)),
system.dataFactory[o]&&a.push(applyFactoryInjectFunction(system.dataFactory[o],t))}}),a}function applyFactoryInjectFunction(e,t){var n=getArguments(e),a=[];return $.each(n,function(e,n){switch(n){case "$root":a.push(t);break;case "$filter":a.push(system.dataFilter);break;case "$req":a.push(new Request(t));break;case "$request":a.push(new Request(t));break;default:system.dataCollection[n]&&a.push(system.dataCollection[n]),system.dataConfig[n]&&a.push(system.dataConfig[n]),system.dataService[n]&&a.push(system.dataService[n]),
system.dataModule[n]&&a.push(new system.dataModule[n](t)),system.dataFactory[n]&&a.push(applyFactoryInjectFunction(system.dataFactory[n],t))}}),e.apply(this,a)}function searchMagicQuout(e){var t=[],n=e.split("^"),a=function(e){return e.replace(/[\r\n]/g,"")};return n.length>1&&$.each(n,function(e,n){if(e)if("("==n.charAt(0)){var o=[];n.replace(/[(*)]/g,function(e,t,n){o.push({index:t,chars:e,mode:")"==e?"close":"open"})});for(var r=0,i=0,s=0,c=0;c<o.length;c++){i++;var l=o[c].mode;if(i&&("open"===
l&&r++,"close"===l&&r--,s=o[c].index,0===r))break}s++;var u=n.substr(0,s),d="-+/*?%".split("");if(d.indexOf(n.substr(s,1))>=0){var m=n.split(" ");t.push(a(m[0]))}else t.push(a(u))}else{var m=n.split(" ");t.push(a(m[0]))}}),t}function inlineRecognize(e,t,n){return $.each(t,function(t,a){var o=codeRecognize(a,n);e=e.replace("^"+a,o)}),e}function codeRecognize(code,root){if("("===code.charAt(0)&&(code=code.replace(/[\)\(]/g,"")),root[code])return root[code];var lineInCode=commandInCode(code);code=lineInCode[0];
try{var result;return function(window){$.each(root,function(e,t){window[e]=t}),result=eval(code),$.each(root,function(e,t){root[e]=window[e],delete window[e]})}(window),lineInCode.length>1?filteringCodeResult(result,lineInCode.splice(1),root):result}catch(e){return""}}function commandInCode(e){if(e.indexOf("|")>=0){var t=e.split("|"),n=[];return $.each(t,function(e,t){if(e){var a=[],o=t.replace(/[\(\)]/g,""),r=o.split(" "),i=[];$.each(r,function(e,t){t&&i.push(t)}),a.push(i[0]);var s=i.splice(1),
c=s.join(""),l=a[0]+" "+c;n.push(l)}else n.push(t.replace(/[\(]/g,""))}),n}return[e]}function filteringCodeResult(result,filters,root){filters=filters[0];var command={},filterName="";if($.each(filters.split(":"),function(i,item){if(i){var cfg=item.split("=");command[cfg[0]]=eval(cfg[1])}else filterName=item.replace(/[ ]/g,"")}),system.dataFilter[filterName]){var args=getArguments(system.dataFilter[filterName]),extArgs={root:root,value:result,config:command},autoArg=getAutoArgument(args,root,extArgs);
return system.dataFilter[filterName].apply(root,autoArg)}return result}function ell(e){var t=document.createElement(e);return $(t)}function toInt(e){return parseInt(e)}function getCommandEach(eachCommand,root){eachCommand=eachCommand.split("|");var commands=eachCommand[0].split(" in ");if(1===commands.length){var dataX=commands[0];commands[0]="keygen_"+parseInt(10*Math.random()),commands[1]=dataX}var dataBinding=commands[1].replace(/[ ]/g,""),args=commands[0].replace(/[\(\)]/g,""),keyArgs=0;if(args.indexOf(",")>
0){var arrArgs=args.split(",");args=arrArgs[1],keyArgs=arrArgs[0]}var advanceCommands={};eachCommand[1]&&$.each(eachCommand[1].split(","),function(e,t){var n=t.split("="),a=n[0].replace(/[ ]/g,"");advanceCommands[a]=n[1].indexOf(["'",'"'])?n[1].replace(/[ ]/g,""):n[1]});var rootDataBinding=root;if(dataBinding.split(".").length>1&&dataBinding.indexOf("$")<0)$.each(dataBinding.split("."),function(e,t){rootDataBinding=rootDataBinding[t]});else if("undefined"==typeof root[dataBinding])try{rootDataBinding=
JSON.parse(dataBinding)}catch(e){rootDataBinding=eval(dataBinding)}else rootDataBinding=""===root[dataBinding]?[]:root[dataBinding];if(keyArgs)args=args.replace(/[ ]/g,"");else if(args.indexOf(" ")>=0){var arrArgs=args.split(" "),newArgs=[];$.each(arrArgs,function(e,t){t&&newArgs.push(t)}),keyArgs=newArgs[0],args=newArgs[1]}if(!root[dataBinding]){var modelGenerate=btoa(dataBinding).substr(0,10);root[modelGenerate]=rootDataBinding,dataBinding=modelGenerate}var cmd={data:rootDataBinding,val:args,key:keyArgs,
advance:advanceCommands,model:dataBinding||""};return cmd}function getALlAttributes(e){var t={};return $.each($(e)[0].attributes,function(e,n){t[n.nodeName]=n.nodeValue}),t}function getFunctionName(e){return e=e.toString(),e.substr(0,e.indexOf("("))}function setModels(e,t){"radio"==e.type||("checkbox"==e.type?e.checked=t:e.type&&$(e).val(t))}function setEventListener(e,t){if(e.type)system.defaultInputEvent[e.type]&&$.each(system.defaultInputEvent[e.type],function(n,a){var o=t||$(e).data("root");e.addEventListener(a,
function(t){if("Control"===t.keyIdentifier||"Right"===t.keyIdentifier||"Left"===t.keyIdentifier||t.ctrlKey)return!1;var n;n="checkbox"===e.type?e.checked:"radio"===e.type?$('input[name="'+e.name+'"]:checked').val():"number"==e.type||"range"==e.type?parseInt($(e).val()):$(e).val(),setRoot(o,e.attributes.model.nodeValue,n),o.apply(),o.$children.length&&o.__starup__&&$.each(o.$children,function(t,a){setRoot(a,e.attributes.model.nodeValue,n),a.apply()})})});else{var n="contenteditable";system.defaultInputEvent[n]&&
$.each(system.defaultInputEvent[n],function(n,a){var o=t||$(e).data("root");e.addEventListener(a,function(t){if("Control"==t.keyIdentifier||"Right"==t.keyIdentifier||"Left"==t.keyIdentifier||t.ctrlKey)return!1;var n=e.innerHTML;setRoot(o,e.attributes.model.nodeValue,n),o.apply()})})}}function setRoot(e,t,n,a){var o=t.split("."),r=e,a=e[t],i=function(){var a=o[0];e[t]?r=1==o.length?r[a]=n:r[a]:1===o.length?r=e.__starup__?r[a]=n:r[a]?r[a]:r[a]=n||r[a]:(r[a]=r[a]||{},r=r[a]),o.splice(0,1),o.length&&
i(o)};i();var s=e.getControllerName();system.dataWatch[s]&&system.dataWatch[s][t]&&!function(){system.dataWatch[s][t].apply(e,[a,e[t]]),e.apply()}()}function getArguments(e){var t=e.toString().replace(/[\r\n ]/g,"");t=t.substr(t.indexOf("(")+1,t.indexOf(")")-(t.indexOf("(")+1));var n=t.split(","),a=[];return $.each(n,function(e,t){t&&a.push(t)}),a}function storeDataInit(textInit,root){var inits=textInit.split(";"),parseIt=function(parse){try{return JSON.parse(parse)}catch(e){return eval(parse)}};
return $.each(inits,function(i,item){var part=item.split("=");try{var key=part[0].replace(/[ ]/g,"");key&&setRoot(root,key,parseIt(part[1]))}catch(e){root[part[0]]=eval(part[1])}}),root}function freeJsController(e,t){t=t||{};var n=$(e).attr("controller")||"controller_"+parseInt(1E3*Math.random());$(e).attr("controller",n),"function"==typeof t?eng.controller(n,t):($(e).data("root",t),eng.controller(n))}function allowTags(e){var t=$(e)[0].tagName.toLowerCase(),n=system.namespace_root.indexOf(t)>=0?
!1:!0,a=!0;return $.each($(e)[0].attributes,function(e,t){system.namespace_root.indexOf(t.nodeName)>=0&&(a=!1)}),a&&n?!0:!1}function _setCookie(e,t,n){n=n||{};var a=function(e){return encodeURIComponent(e)},o=function(e){return a("object"==typeof e?JSON.stringify(e):String(e))};if("number"==typeof n.expires){var r=n.expires,i=n.expires=new Date;i.setTime(+i+864E5*r)}return document.cookie=[a(e),"=",o(t),n.expires?"; expires="+n.expires.toUTCString():"",n.path?"; path="+n.path:"",n.domain?"; domain="+
n.domain:"",n.secure?"; secure":""].join("")}function _getCookie(e){for(var t,n=function(e){return decodeURIComponent(e)},a=document.cookie?document.cookie.split("; "):[],o=0;o<a.length;o++){var r=a[o].split("=");if(n(r[0])===e){t=r[1];break}}return t}function _removeCookie(e){return void 0===_getCookie(e)?!1:(_setCookie(e,"",{expires:-1}),_getCookie(e))}function getAllTags(e){e=$(e);var t=[],n=function(e){var a=$(e)[0].tagName.toLowerCase();if(system.blocking_tags.indexOf(a)<0){system.dataDirective[a]&&
t.push({action:"directive",name:a,element:$(e)[0]});var o=$(e)[0].attributes;$.each(o,function(n,a){if(system.dataTagDirective[a.nodeName])t.push({action:"tagDirective",name:a.nodeName,element:a,parent:$(e)[0]});else{var o=searchMagicQuout(a.nodeValue);o.length&&t.push({action:"codeRecognize",original:a.nodeValue,name:a.nodeName,element:a,parent:$(e)[0]}),system.allEvents.indexOf(a.nodeName)>=0&&t.push({action:"events",original:a.nodeValue,name:a.nodeName,element:a,parent:$(e)[0]})}}),$.each($(e)[0].childNodes,
function(e,a){if("#text"===a.nodeName){var o=searchMagicQuout(a.nodeValue);o.length&&t.push({action:"codeRecognize",original:a.nodeValue,name:a.nodeName,element:a})}else allowTags(a)?n(a):$.each(a.attributes,function(e,n){system.dataTagDirective[n.nodeName]&&t.push(system.namespace_root.indexOf(n.nodeName)>=0?{action:n.nodeName,original:n.nodeValue,name:n.nodeName,element:n,parent:a}:{action:"tagDirective",name:n.nodeName,element:n,parent:a})})})}};n(e);var a=0,o={};return $.each(t,function(e,t){e&&
(a++,o["#id"+a]=t)}),o}function extendsRoot(e,t){var n=["__starup__","getControllerName","$children"];$.each(t,function(t,a){n.indexOf(t)<0&&(e[t]=a)})}function Collection(e){this.structure=e||{},this.store=[],this.onChange=function(){}}function Request(e){this.root=e,this.$get=function(t,n){if("object"!=typeof t)return this.addToLiveRequest(t,"GET",n),t;if(t.type="GET",t.target){var a=t.success||function(e){return e},o=function(n){n=a(n),$(t.target).html(n),freeJsController($(t.target),e)};t.success=
null,t.success=o}$.ajax(t)},this.$post=function(t,n){if("object"!=typeof t)return this.addToLiveRequest(t,"POST",n),t;if(t.type="POST",t.target){var a=t.success||function(e){return e},o=function(n){n=a(n),$(t.target).html(n),freeJsController($(t.target),e)};t.success=null,t.success=o}$.ajax(t)},this.$json=function(t,n){if("object"!=typeof t)return this.addToLiveRequest(t,"GET",n),t;if(t.type="GET",t.target){var a=t.success||function(e){return e},o=function(n){n=a(n),$(t.target).html(n),freeJsController($(t.target),
e)};t.success=null,t.success=o}$.ajax(t)},this.addToLiveRequest=function(t,n,a){a=a||{},system.dataLiveRequest.push({type:n,url:t,data:a})}}function getRoute(){var e="",t=function(e){e=e.split("/");for(var t=[],n=0;n<e.length;n++)e[n]&&t.push(e[n]);return t},n=window.location.hash||"/";n=n.replace("#","");var a=!1;return $.each(system.dataRoute,function(o,r){if(!a)if(o===n)a=!0,e=o;else{var i=t(n),s=t(o);if(i.length>=s.length)for(var c=0;c<i.length;c++)i[c]!==s[c]&&"*"===s[c]&&(e||(e=o));else n+"*"===
o&&(e=n+"*")}}),e}function goRoute(){function e(e){if("string"==typeof e.controller)system.dataController[e.controller]&&(system.dataController[e.controller].$root.route=o.data,e.boxController.data("root",system.dataController[e.controller].$root),freeJsController(e.boxController,system.dataController[e.controller].callback));else{e.controller=e.controller||function(){};var t={},n=getArguments(e.controller);getAutoArgument(n,t);freeJsController(e.boxController,e.controller)}}var t=window.location.hash.replace("#",
""),n=getRoute();if(!n)return!1;var a=system.dataRoute[n],o=(getArguments(a),a.apply(this,[t]));o.boxController=eng.ell("div").data({isroute:!0}),$('[route="'+o.target+'"]').html(o.boxController),o.templateUrl?o.enableCache&&ROUTE_CACHE[o.templateUrl]?(o.template=ROUTE_CACHE[o.templateUrl],o.boxController.html(o.template),e(o)):$.ajax({url:o.templateUrl,type:o.method||"GET",data:o.data||{},success:function(t){o.boxController.html(t),ROUTE_CACHE[o.templateUrl]=o.template=t,e(o)},error:function(){console.error('No files found : "',
o.templateUrl,'"')}}):e(o)}var eng=window.eng||(window.eng={});eng.versions={number:"0.0.2",rev:"8-1-15"};var root="root",binding="binding",init="init",model="model",controller="controller",each="each",system={blocking_tags:["script"],namespace_root:[controller,each],dataController:{},dataDirective:{},dataTagDirective:{},dataFilter:{},allEvents:"abort,autocomplete,autocompleteerror,beforecopy,beforecut,beforepaste,blur,cancel,canplay,canplaythrough,change,click,close,contextmenu,copy,cuechange,cut,dblclick,drag,dragend,dragenter,dragleave,dragover,dragstart,drop,durationchange,emptied,ended,error,focus,input,invalid,keydown,keypress,keyup,load,loadeddata,loadedmetadata,loadstart,mousedown,mouseenter,mouseleave,mousemove,mouseout,mouseover,mouseup,mousewheel,paste,pause,play,playing,progress,ratechange,reset,resize,scroll,search,seeked,seeking,select,selectstart,show,stalled,submit,suspend,timeupdate,toggle,volumechange,waiting,webkitfullscreenchange,webkitfullscreenerror,wheel".split(","),
defaultInputEvent:{contenteditable:["keyup"],text:["keyup"],search:["keyup","change"],email:["keyup"],url:["keyup"],radio:["change"],date:["change"],month:["change"],color:["change"],year:["change"],week:["change"],range:["mousemove","change"],number:["keyup","change"],checkbox:["click"],textarea:["keyup"],"select-one":["change"],"select-multiple":["change"]},dataCollection:{},dataConfig:{},dataService:{},dataModule:{},dataRoute:{},dataFactory:{},dataWatch:{},dataLiveRequest:[],dataCacheLiveRequest:{}};
eng.controller=function(e,t){return $(document).ready(function(){return system.dataTagDirective[controller](e,t),eng}),eng},eng.directive=function(e,t){return system.dataDirective[e]=t,eng},eng.tagDirective=function(e,t){return system.dataTagDirective[e]=t,eng},eng.filter=function(e,t){return system.dataFilter[e]=t,eng},eng.tagDirective=function(e,t){return _tagDirective(e,t)},eng.directive=function(e,t){return _directive(e,t)},eng.collection=function(e,t){return _collection(e,t)},eng.config=function(e,
t){return _config(e,t)},eng.service=function(e,t){return _service(e,t)},eng.module=function(e,t){return _module(e,t)},eng.factory=function(e,t){return _factory(e,t)},eng.route=function(e,t){return _route(e,t)},eng.$watchProvide=function(e,t){system.dataWatch[e][t]()},Array.prototype.findBy=function(e){if(!this.length)return[];var t=[],n=[],a={},o={};return $.each(this[0],function(e,t){n.push(e)}),$.each(this,function(e,t){a[e]=t}),$.each(a,function(t,a){$.each(n,function(n,r){a[r].indexOf(e)>=0&&
(o[t]=a)})}),$.each(o,function(e,n){t.push(n)}),t},eng.tagDirective(each,function(e,t,n){var a,o,r,i,s=getALlAttributes(t);a=getCommandEach(s.each,n),a.advance.total=a.advance.total||"$count",o=n[a.model],a.val||(a.val=a.key,a.key="");var c=!1;if($(t).data("execute")){var l=$(t).data("length");if(o.length===l)return!1;$(t).empty().data({length:o.length,dataBinding:o}),i=$(t).data("template")}else{if(c)return!1;r=$(t).clone(),i=r.html(),$(t).empty().data({execute:!0,template:i,length:o.length})}var u=
!1,d=o,m=a.advance.sort?codeRecognize(a.advance.sort,n):void 0,f=a.advance.sortBy?codeRecognize(a.advance.sortBy,n):void 0,g=a.advance.filter?codeRecognize(a.advance.filter,n):void 0;if(void 0!==m)if(void 0!==f)if(void 0!==g){var d=d.findBy(g);m?d.sortBy(f):d.reverseBy(f)}else{d.findBy("");m?d.sortBy(f):d.reverseBy(f)}else m&&d.sort();var p=function(e){$(t).empty();var o=0;n[a.advance.total]=e.length,n.$children=[],$.each(e,function(r,s){var c="controller_"+o+"_"+parseInt(1E6*Math.random()),l=$(i).attr("controller",
c);$(t).append(l),l.data({children:!0,parent:n,model:a.model});var u={};extendsRoot(u,n),u.$index=o,u.$global=n,u[a.advance.total]=e.length,u.$number=o+1,u.$parents={},u[a.key]=r,u[a.val]=e[r],u.$parents[a.val]=a.model,freeJsController(l,u),o++,n.$children.push(u),delete system.dataController[c]})};if(!u){if(p(d),$(t).attr("watch-id")){var h=$(t).attr("watch-id");n.watch(h,function(e,t){c=!0,setTimeout(function(){p(n[a.model]),c=!1},10)})}void 0!==m&&(void 0!==f?n.watch(a.advance.sort,function(e,
t){if(void 0!==g){m=a.advance.sort?codeRecognize(a.advance.sort,n):void 0,f=a.advance.sortBy?codeRecognize(a.advance.sortBy,n):void 0;var o=codeRecognize(a.advance.filter,n),r=d.findBy(o);r.sort().reverse(),m?r.sortBy(f):r.reverseBy(f),c=!0,setTimeout(function(){p(r),c=!1},10)}else{var r=d.findBy("");t?r.sortBy(f):r.reverseBy(f),c=!0,setTimeout(function(){p(r),c=!1},10)}}):n.watch(a.advance.sort,function(e,t){if(void 0!==g){var o=codeRecognize(a.advance.filter,n),r=d.findBy(o);r.sort().reverse(),
t&&r.sort(),c=!0,setTimeout(function(){p(r),c=!1},10)}else{var r=d.findBy("");r.sort().reverse(),t&&r.sort(),c=!0,setTimeout(function(){p(r),c=!1},10)}})),void 0!==g&&n.watch(a.advance.filter,function(e,t){g=a.advance.filter?codeRecognize(a.advance.filter,n):void 0;var o=d.findBy(t);o.sort().reverse(),t?c||p(o):e!==t&&(c||p(d))})}if(n.apply(),system.defaultInputEvent[t.type]&&t.attributes.model){var y=codeRecognize(t.attributes.model.nodeValue,n);t.value=y}u=!0}),eng.tagDirective(binding,function(value,
element,root){var e=value,t=element,n=root;$(t).html(e)}),eng.tagDirective(init,function(value,element,root){var e=value,t=element,n=root;storeDataInit(e,n)}),eng.tagDirective(model,function(value,element,root){var e=value,t=element,n=root;if("string"==typeof t.value)if("checkbox"===t.type)"undefined"==typeof n[t.attributes.model.nodeValue]&&(n[t.attributes.model.nodeValue]=t.checked),t.checked=n[t.attributes.model.nodeValue];else if("radio"===t.type)"undefined"==typeof n[t.attributes.model.nodeValue]&&
(n[t.attributes.model.nodeValue]=$('input[name="'+t.name+'"]:checked').val()||""),t.checked=n[t.attributes.model.nodeValue];else if(t.attributes.model.nodeValue.indexOf(".")>0)setRoot(n,t.attributes.model.nodeValue,t.valueAsNumber||t.value);else{var a=t.valueAsNumber||t.value,o=n[t.attributes.model.nodeValue]||a;n[t.attributes.model.nodeValue]=o}else t.isContentEditable&&(n[t.attributes.model.nodeValue]=t.innerHTML);$(t).data({root:n}),setEventListener(t,n)}),eng.tagDirective(controller,function(controllerName,
callback){callback=callback||function(){};var node=$("["+controller+'="'+controllerName+'"]'),$root=node.data("root")?node.data("root"):{};if($root.__starup__=0,$root.$children=[],$root.getControllerName=function(){return controllerName},system.dataController[controllerName]={callback:callback,$root:$root},!node.length)return!1;$root.watch=function(e,t){system.dataWatch[controllerName]=system.dataWatch[controllerName]||{},system.dataWatch[controllerName][e]=t},$root.$reset=function(e){var t={};return extendsRoot(t,
$root),freeJsController(e,t)},$.each(getAllTags(node),function(e,t){if(system.dataDirective[t.name]&&system.namespace_root.indexOf(t.name)<0){var n=getALlAttributes(t.element),a=getArguments(system.dataDirective[t.name]),o={"root":$root,"element":t.element,"attribute":n},r=getAutoArgument(a,$root,o);system.dataDirective[t.name].apply($root,r)}});var allTags=getAllTags(node);$.each(allTags,function(e,t){t.name===init&&(system.dataTagDirective.init(t.element.nodeValue,t.parent,$root),delete allTags[e])});
var args=getArguments(callback),autoArg=getAutoArgument(args,$root);callback.apply($root,autoArg),node.data("children");var rootGenerate=function(){var tagModels=[];$.each(allTags,function(e,t){"model"===t.name&&(tagModels.push(t),system.dataTagDirective.model(t.element.nodeValue,t.parent,$root),delete allTags[e])});var applyTagDirective=function(e){$.each(allTags,function(t,n){if(system.dataTagDirective[n.name]&&system.namespace_root.indexOf(n.name)<0){var a=getArguments(system.dataTagDirective[n.name]),
o={value:codeRecognize(n.element.nodeValue,e),element:n.parent,root:e},r=getAutoArgument(a,$root,o);system.dataTagDirective[n.name].apply(e,r)}})};applyTagDirective($root);var applyText=function(e){$.each(allTags,function(t,n){if("codeRecognize"===n.action){var a=searchMagicQuout(n.original),o=inlineRecognize(n.original,a,e);n.element.nodeValue=o}})};applyText($root);var applyModel=function(e){$.each(tagModels,function(t,n){var a=codeRecognize(n.element.nodeValue,e,n);n.element.nodeValue.indexOf(".")>
0||($root[n.element.nodeValue]=a),setModels(n.parent,a)})};applyModel($root);var circularFunction=function(e){$.each(allTags,function(t,n){system.dataTagDirective[n.name]&&system.namespace_root.indexOf(n.name)>=0&&("controller"===n.action||system.dataTagDirective[n.name](codeRecognize(n.element.nodeValue,e),n.parent,e))})},applyRoot;"function"==typeof $root.apply&&(applyRoot=$root.apply,$root.apply=null),$root.apply=function(){if(applyModel($root),applyTagDirective($root),applyText($root),circularFunction($root),
"function"==typeof applyRoot){var e=node.data();e.parent&&e.parent.__starup__&&applyRoot()}},$root.apply(),$.each(allTags,function(___i__,__item__){"events"===__item__.action&&__item__.parent.addEventListener(__item__.name,function(e){if("Control"===e.keyIdentifier||"Right"===e.keyIdentifier||"Left"===e.keyIdentifier||e.ctrlKey)return!1;var $before={};$.extend($before,$root),e.root=$root,$root.$$event=e,$root.$$this=__item__.parent;var ret,codes=__item__.element.nodeValue,cekFoo=getFunctionName(codes);
"function"==typeof $root[cekFoo]?($.each($root,function(e,t){window[e]=t}),ret=eval($root.$global?"$root.$global."+codes:"$root."+codes),$.each($root,function(e,t){delete window[e]})):ret=codeRecognize(codes,$root),delete $root.$$event,delete $root.$$this,$root.apply();var ctrlName=controllerName;$.each($root,function(e,t){system.dataWatch[ctrlName]&&system.dataWatch[ctrlName][e]&&(system.dataWatch[ctrlName][e].apply($root,[$before[e],$root[e]]),$root.apply())})})}),$root.__starup__=1};if(node.data("isroute"))return rootGenerate(),
!1;if(system.dataLiveRequest.length){var getsReq=function(){if(system.dataLiveRequest.length){var e=new Request,t="$"+system.dataLiveRequest[0].type.toLowerCase();e[t]({type:system.dataLiveRequest[0].type,url:system.dataLiveRequest[0].url,data:system.dataLiveRequest[0].data,success:function(e){system.dataLiveRequest[0]&&(system.dataCacheLiveRequest[system.dataLiveRequest[0].url]="json"==t?JSON.parse(t):e,system.dataLiveRequest.splice(0,1),getsReq())}})}else $.each(system.dataService,function(e,t){$.each(t,
function(t,n){system.dataCacheLiveRequest[t]&&(system.dataService[e][t]=system.dataCacheLiveRequest[t])})}),$.each($root,function(e,t){system.dataCacheLiveRequest[t]&&(delete $root[e],$root[e]=system.dataCacheLiveRequest[t],delete system.dataCacheLiveRequest[t])}),rootGenerate()};getsReq()}else rootGenerate()});var dateFormat=function(){var e=/d{1,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,t=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,
n=/[^-+\dA-Z]/g,a=function(e,t){for(e=String(e),t=t||2;e.length<t;)e="0"+e;return e};return function(o,r,i){var s=dateFormat;if(1!=arguments.length||"[object String]"!=Object.prototype.toString.call(o)||/\d/.test(o)||(r=o,o=void 0),o=o?new Date(o):new Date,isNaN(o))throw SyntaxError("invalid date");r=String(s.masks[r]||r||s.masks["default"]),"UTC:"==r.slice(0,4)&&(r=r.slice(4),i=!0);var c=i?"getUTC":"get",l=o[c+"Date"](),u=o[c+"Day"](),d=o[c+"Month"](),m=o[c+"FullYear"](),f=o[c+"Hours"](),g=o[c+"Minutes"](),
p=o[c+"Seconds"](),h=o[c+"Milliseconds"](),y=i?0:o.getTimezoneOffset(),v={d:l,dd:a(l),ddd:s.i18n.dayNames[u],dddd:s.i18n.dayNames[u+7],m:d+1,mm:a(d+1),mmm:s.i18n.monthNames[d],mmmm:s.i18n.monthNames[d+12],yy:String(m).slice(2),yyyy:m,h:f%12||12,hh:a(f%12||12),H:f,HH:a(f),M:g,MM:a(g),s:p,ss:a(p),l:a(h,3),L:a(h>99?Math.round(h/10):h),t:12>f?"a":"p",tt:12>f?"am":"pm",T:12>f?"A":"P",TT:12>f?"AM":"PM",Z:i?"UTC":(String(o).match(t)||[""]).pop().replace(n,""),o:(y>0?"-":"+")+a(100*Math.floor(Math.abs(y)/
60)+Math.abs(y)%60,4),S:["th","st","nd","rd"][l%10>3?0:(l%100-l%10!=10)*l%10]};return r.replace(e,function(e){return e in v?v[e]:e.slice(1,e.length-1)})}}();dateFormat.masks={"default":"ddd mmm dd yyyy HH:MM:ss",shortDate:"m/d/yy",mediumDate:"mmm d, yyyy",longDate:"mmmm d, yyyy",fullDate:"dddd, mmmm d, yyyy",shortTime:"h:MM TT",mediumTime:"h:MM:ss TT",longTime:"h:MM:ss TT Z",isoDate:"yyyy-mm-dd",isoTime:"HH:MM:ss",isoDateTime:"yyyy-mm-dd'T'HH:MM:ss",isoUtcDateTime:"UTC:yyyy-mm-dd'T'HH:MM:ss'Z'"},
dateFormat.i18n={dayNames:["Sun","Mon","Tue","Wed","Thu","Fri","Sat","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],monthNames:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec","January","February","March","April","May","June","July","August","September","October","November","December"]},Collection.prototype.insert=function(e){var t=this,n=Date.now()+""+parseInt(1E3*Math.random());n=parseInt(n.replace(".",""));var a=Date.now();if(e instanceof Array&&
this.structure instanceof Object){var o={},r=0;$.each(this.structure,function(t,n){o[t]=typeof e[r]===n?e[r]:"",r++}),o.__id=n,o.__update=a,o.__create=a,this.store.push(o)}else $.each(e,function(e,n){t.structure[e]=n instanceof Object?"object":n.getType()}),e.__id=n,e.__update=a,e.__create=a,this.store.push(e);return this.onChange(),this},Collection.prototype.remove=function(e){var t=this,n=[];if("object"!=typeof e){var a;return $.each(this.store,function(t,n){n.__id==e.toString()&&(a=t)}),a>=0&&
t.store.splice(a,1),this.onChange(),this}$.each(this.store,function(t,a){$.each(a,function(a,o){$.each(e,function(e,r){e==a&&r==o&&n.push(t)})})});var o=0;return $.each(n,function(e,n){t.store.splice(n-o,1),o++}),this.onChange(),this},Collection.prototype.get=function(e){var t=[];return"object"!=typeof e?($.each(this.store,function(n,a){a.__id==e&&t.push(a)}),t):($.each(this.store,function(n,a){$.each(a,function(n,o){$.each(e,function(e,r){e==n&&r==o&&t.push(a)})})}),t)},Collection.prototype.find=
function(e){var t=[];return $.each(this.store,function(n,a){$.each(a,function(n,o){$.each(e,function(e,r){e==n&&o.indexOf(r)>=0&&t.push(a)})})}),t},Collection.prototype.set=function(e){var t=this,n={};return n.by=function(n){var a=t.get(n);return $.each(a,function(t,n){n.__update=Date.now(),$.extend(n,e)}),t.onChange(),a},n},eng.ell=ell,eng.setCookie=function(e,t,n){return _setCookie(e,t,n)},eng.getCookie=function(e){return _getCookie(e)},eng.removeCookie=function(e){return _removeCookie(e)};var ROUTE_CACHE=
{};window.onpopstate=goRoute,Array.prototype.sortBy=function(e){this.sort(function(t,n){return t[e]<n[e]?-1:t[e]>n[e]?1:0})},Array.prototype.reverseBy=function(e){this.sort(function(t,n){return t[e]>n[e]?-1:t[e]<n[e]?1:0})};var STD_WIDGET=!0;STD_WIDGET&&(eng.filter("date",function(value,config){var e=value,t=config;return dateFormat(new Date(e),t.format)}),eng.filter("upper",function(value,config){var e=value,t=config;return e.toUpperCase()}),eng.filter("lower",function(value,config){var e=value,
t=config;return e.toLowerCase()}),eng.filter("ucfirst",function(value,config){var e=value,t=config;return e.substr(0,1).toUpperCase()+e.substr(1,e.length).toLowerCase()}),eng.filter("sorting",function(value,config){var e=value,t=config;var n=[],a=[],o={};return $.each(e,function(e,n){o[n[t.key]+"_"+e]=n,a.push(n[t.key]+"_"+e)}),t.sort?a.sort():a.sort().reverse(),$.each(a,function(e,t){n.push(o[t])}),n}),eng.filter("comma",function(value,config){var e=value,t=config;return e/parseInt(t.decimal)}),
eng.filter("toInt",function(value,config){var e=value,t=config;return parseInt(e)}),eng.filter("src",function(value,config){var e=value,t=config;var n=new FileReader;n.onload=function(){e.root[t.model]={src:n.result,info:e.target.files[0]},e.root.apply()},n.readAsDataURL(e.target.files[0])}),eng.filter("mid",function(value,config){var e=value,t=config;return e.substr(t.point1,t.point2)}),eng.filter("length",function(value,config){var e=value,t=config;return e.length}),eng.filter("json",function(value,
config){var e=value,t=config;return JSON.stringify(e)}),eng.directive("checkbox",function(element,attribute){var t=element,n=attribute;var a="id_"+Math.floor(1E4*Math.random()),o=ell("input").attr({type:"checkbox",model:n.model,id:a}),r=ell("label").attr("for",a).html(n.label);r.insertAfter($(t)),o.insertAfter($(t)),$(t).remove()}),eng.directive("form",function(value,element,root){var e=value,t=element,n=root;if(n.action){var a=getFunctionName(n.action);setTimeout(function(){e[a]&&($(t).attr({type:"POST",
action:"javascript:false;"}),t.addEventListener("submit",function(t){return t.stopPropagation(),t.stopImmediatePropagation(),codeRecognize(n.action,e)}))},10)}}),eng.tagDirective("show",function(value,element,root){var e=value,t=element,n=root;var a=e;a?$(t).show():$(t).hide()}),eng.tagDirective("hide",function(value,element,root){var e=value,t=element,n=root;var a=e;a?$(t).hide():$(t).show()}),eng.tagDirective("_disabled",function(value,element,root){var e=value,t=element,n=root;var a=e;a?$(t).attr({disabled:!0}):
$(t).removeAttr("disabled")}),eng.tagDirective("_checked",function(value,element,root){var e=value,t=element,n=root;var a=e;a?$(t)[0].checked=!0:$(t)[0].checked=!1}),eng.tagDirective("_readonly",function(value,element,root){var e=value,t=element,n=root;var a=e;a?$(t).attr({readonly:"readonly"}):$(t).removeAttr("readonly")}),eng.tagDirective("view",function(value,element,root){var e=value,t=element,n=root;var a=e;if(a){var o=$(t).attr("model");$(t).data("value")!=n[o]&&($(t).data("value",n[o]),$.ajax({url:n[o],
success:function(e){$(t).html(e)}}))}}),eng.tagDirective("template",function(value,element,root){var e=value,t=element,n=root;var a=e,o=a||$(t).attr("template");if(o&&$(t).attr("value")!=o){$(t).attr("value",o);var r=$('script[name="'+o+'"]').clone().html(),i=ell("div").append(r);$(t).html(i);var s={};extendsRoot(s,n),freeJsController(i,s)}})),$(document).ready(function(){$("[controller]").each(function(e,t){var n=$(t).attr("controller");n?setTimeout(function(){system.dataController[n]||freeJsController(t)},
10):freeJsController(t)}),setTimeout(function(){goRoute()},100)})}(window,document);
